# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 550)
        Dialog.setMinimumSize(QtCore.QSize(400, 550))
        Dialog.setMaximumSize(QtCore.QSize(400, 550))
        Dialog.setToolTip("")
        Dialog.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(42, 59, 36, 255), stop:0.465909 rgba(66, 120, 70, 255), stop:0.98 rgba(47, 111, 37, 255), stop:1 rgba(0, 0, 0, 0));\n"
"QFrame{\n"
"background:rgba(0,0,10,0.5);\n"
"border-radius:15px;\n"
"}\n"
"QLineEdit{\n"
"background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 381, 571))
        self.stackedWidget.setStyleSheet("background:transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_inicio = QtWidgets.QWidget()
        self.page_inicio.setObjectName("page_inicio")
        self.frame = QtWidgets.QFrame(self.page_inicio)
        self.frame.setGeometry(QtCore.QRect(10, 0, 361, 511))
        self.frame.setStyleSheet("QFrame{\n"
"background:rgba(0,0,10,0.5);\n"
"border-radius:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_inicio = QtWidgets.QLabel(self.frame)
        self.lbl_inicio.setGeometry(QtCore.QRect(40, 70, 291, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio.setFont(font)
        self.lbl_inicio.setStyleSheet("background:transparent;")
        self.lbl_inicio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio.setObjectName("lbl_inicio")
        self.lbl_inicio_ingreso = QtWidgets.QLabel(self.frame)
        self.lbl_inicio_ingreso.setGeometry(QtCore.QRect(10, 140, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso.setFont(font)
        self.lbl_inicio_ingreso.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso.setObjectName("lbl_inicio_ingreso")
        self.btn_sumar = QtWidgets.QPushButton(self.frame)
        self.btn_sumar.setGeometry(QtCore.QRect(60, 280, 241, 41))
        self.btn_sumar.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"QPushButton:hover{\n"
"color: white;\n"
"border-bottom:1px solid white;\n"
"border-top:1px solid white;\n"
"border-left:1px solid white;\n"
"border-right:1px solid white;\n"
"font-weigth:bold;\n"
"border-radius:18px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icon_entrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sumar.setIcon(icon)
        self.btn_sumar.setIconSize(QtCore.QSize(20, 20))
        self.btn_sumar.setObjectName("btn_sumar")
        self.btn_multiplicar = QtWidgets.QPushButton(self.frame)
        self.btn_multiplicar.setGeometry(QtCore.QRect(60, 330, 241, 41))
        self.btn_multiplicar.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"QPushButton:hover{\n"
"color: white;\n"
"border-bottom:1px solid white;\n"
"border-top:1px solid white;\n"
"border-left:1px solid white;\n"
"border-right:1px solid white;\n"
"font-weigth:bold;\n"
"border-radius:18px;\n"
"}")
        self.btn_multiplicar.setIcon(icon)
        self.btn_multiplicar.setIconSize(QtCore.QSize(20, 20))
        self.btn_multiplicar.setObjectName("btn_multiplicar")
        self.txt_num_1 = QtWidgets.QLineEdit(self.frame)
        self.txt_num_1.setGeometry(QtCore.QRect(50, 210, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_num_1.setFont(font)
        self.txt_num_1.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_num_1.setMaxLength(1000000000)
        self.txt_num_1.setObjectName("txt_num_1")
        self.txt_num_2 = QtWidgets.QLineEdit(self.frame)
        self.txt_num_2.setGeometry(QtCore.QRect(210, 210, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_num_2.setFont(font)
        self.txt_num_2.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_num_2.setMaxLength(1000000000)
        self.txt_num_2.setObjectName("txt_num_2")
        self.lbl_inicio_opcion = QtWidgets.QLabel(self.frame)
        self.lbl_inicio_opcion.setGeometry(QtCore.QRect(0, 230, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_opcion.setFont(font)
        self.lbl_inicio_opcion.setStyleSheet("background:transparent;")
        self.lbl_inicio_opcion.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_opcion.setObjectName("lbl_inicio_opcion")
        self.lbl_inicio_saludo_4 = QtWidgets.QLabel(self.frame)
        self.lbl_inicio_saludo_4.setGeometry(QtCore.QRect(10, 410, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_saludo_4.setFont(font)
        self.lbl_inicio_saludo_4.setStyleSheet("background:transparent;")
        self.lbl_inicio_saludo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_saludo_4.setObjectName("lbl_inicio_saludo_4")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(90, 450, 201, 21))
        self.comboBox.setStyleSheet("color :white;\n"
"background-color:rgb(85, 85, 85,0.05);\n"
"border: none;\n"
"font-family: calibri;\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lbl_inicio_saludo_5 = QtWidgets.QLabel(self.frame)
        self.lbl_inicio_saludo_5.setGeometry(QtCore.QRect(20, 370, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_saludo_5.setFont(font)
        self.lbl_inicio_saludo_5.setStyleSheet("background:transparent;")
        self.lbl_inicio_saludo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_saludo_5.setObjectName("lbl_inicio_saludo_5")
        self.lbl_resultado_oper_basicas = QtWidgets.QLabel(self.frame)
        self.lbl_resultado_oper_basicas.setGeometry(QtCore.QRect(130, 370, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_resultado_oper_basicas.setFont(font)
        self.lbl_resultado_oper_basicas.setStyleSheet("background:transparent;")
        self.lbl_resultado_oper_basicas.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_resultado_oper_basicas.setObjectName("lbl_resultado_oper_basicas")
        self.stackedWidget.addWidget(self.page_inicio)
        self.page_ecuaciones = QtWidgets.QWidget()
        self.page_ecuaciones.setObjectName("page_ecuaciones")
        self.page_ecuacion = QtWidgets.QFrame(self.page_ecuaciones)
        self.page_ecuacion.setGeometry(QtCore.QRect(10, 10, 361, 511))
        self.page_ecuacion.setStyleSheet("QFrame{\n"
"background:rgba(0,0,10,0.5);\n"
"border-radius:15px;\n"
"}")
        self.page_ecuacion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_ecuacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_ecuacion.setObjectName("page_ecuacion")
        self.lbl_inicio_2 = QtWidgets.QLabel(self.page_ecuacion)
        self.lbl_inicio_2.setGeometry(QtCore.QRect(20, 30, 331, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_2.setFont(font)
        self.lbl_inicio_2.setStyleSheet("background:transparent;")
        self.lbl_inicio_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_2.setObjectName("lbl_inicio_2")
        self.lbl_inicio_ingreso_2 = QtWidgets.QLabel(self.page_ecuacion)
        self.lbl_inicio_ingreso_2.setGeometry(QtCore.QRect(10, 120, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_2.setFont(font)
        self.lbl_inicio_ingreso_2.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_2.setObjectName("lbl_inicio_ingreso_2")
        self.btn_cuadratica_solucion = QtWidgets.QPushButton(self.page_ecuacion)
        self.btn_cuadratica_solucion.setGeometry(QtCore.QRect(60, 300, 241, 41))
        self.btn_cuadratica_solucion.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"QPushButton:hover{\n"
"color: white;\n"
"border-bottom:1px solid white;\n"
"border-top:1px solid white;\n"
"border-left:1px solid white;\n"
"border-right:1px solid white;\n"
"font-weigth:bold;\n"
"border-radius:18px;\n"
"}")
        self.btn_cuadratica_solucion.setIcon(icon)
        self.btn_cuadratica_solucion.setIconSize(QtCore.QSize(20, 20))
        self.btn_cuadratica_solucion.setObjectName("btn_cuadratica_solucion")
        self.txt_cuadratica_a = QtWidgets.QLineEdit(self.page_ecuacion)
        self.txt_cuadratica_a.setGeometry(QtCore.QRect(10, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.txt_cuadratica_a.setFont(font)
        self.txt_cuadratica_a.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_cuadratica_a.setMaxLength(1000000000)
        self.txt_cuadratica_a.setObjectName("txt_cuadratica_a")
        self.lbl_inicio_ingreso_3 = QtWidgets.QLabel(self.page_ecuacion)
        self.lbl_inicio_ingreso_3.setGeometry(QtCore.QRect(10, 150, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_3.setFont(font)
        self.lbl_inicio_ingreso_3.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_3.setObjectName("lbl_inicio_ingreso_3")
        self.txt_cuadratica_b = QtWidgets.QLineEdit(self.page_ecuacion)
        self.txt_cuadratica_b.setGeometry(QtCore.QRect(150, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.txt_cuadratica_b.setFont(font)
        self.txt_cuadratica_b.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_cuadratica_b.setMaxLength(1000000000)
        self.txt_cuadratica_b.setObjectName("txt_cuadratica_b")
        self.txt_cuadratica_c = QtWidgets.QLineEdit(self.page_ecuacion)
        self.txt_cuadratica_c.setGeometry(QtCore.QRect(300, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.txt_cuadratica_c.setFont(font)
        self.txt_cuadratica_c.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_cuadratica_c.setMaxLength(1000000000)
        self.txt_cuadratica_c.setObjectName("txt_cuadratica_c")
        self.lbl_inicio_ingreso_4 = QtWidgets.QLabel(self.page_ecuacion)
        self.lbl_inicio_ingreso_4.setGeometry(QtCore.QRect(90, 220, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_4.setFont(font)
        self.lbl_inicio_ingreso_4.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_4.setObjectName("lbl_inicio_ingreso_4")
        self.lbl_inicio_ingreso_5 = QtWidgets.QLabel(self.page_ecuacion)
        self.lbl_inicio_ingreso_5.setGeometry(QtCore.QRect(230, 220, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_5.setFont(font)
        self.lbl_inicio_ingreso_5.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_5.setObjectName("lbl_inicio_ingreso_5")
        self.lbl_inicio_ingreso_6 = QtWidgets.QLabel(self.page_ecuacion)
        self.lbl_inicio_ingreso_6.setGeometry(QtCore.QRect(10, 350, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_6.setFont(font)
        self.lbl_inicio_ingreso_6.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_6.setObjectName("lbl_inicio_ingreso_6")
        self.lbl_solucion_cuadratica = QtWidgets.QLabel(self.page_ecuacion)
        self.lbl_solucion_cuadratica.setGeometry(QtCore.QRect(10, 400, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.lbl_solucion_cuadratica.setFont(font)
        self.lbl_solucion_cuadratica.setStyleSheet("background:transparent;\n"
"color: white;")
        self.lbl_solucion_cuadratica.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_solucion_cuadratica.setObjectName("lbl_solucion_cuadratica")
        self.btn_regresar_cuadratica = QtWidgets.QPushButton(self.page_ecuaciones)
        self.btn_regresar_cuadratica.setGeometry(QtCore.QRect(330, 10, 41, 41))
        self.btn_regresar_cuadratica.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"")
        self.btn_regresar_cuadratica.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icon_salir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regresar_cuadratica.setIcon(icon1)
        self.btn_regresar_cuadratica.setObjectName("btn_regresar_cuadratica")
        self.stackedWidget.addWidget(self.page_ecuaciones)
        self.page_pendiente = QtWidgets.QWidget()
        self.page_pendiente.setObjectName("page_pendiente")
        self.frame_3 = QtWidgets.QFrame(self.page_pendiente)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 361, 511))
        self.frame_3.setStyleSheet("QFrame{\n"
"background:rgba(0,0,10,0.5);\n"
"border-radius:15px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_inicio_3 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_3.setGeometry(QtCore.QRect(20, 50, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_3.setFont(font)
        self.lbl_inicio_3.setStyleSheet("background:transparent;")
        self.lbl_inicio_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_3.setObjectName("lbl_inicio_3")
        self.lbl_inicio_ingreso_7 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_7.setGeometry(QtCore.QRect(10, 120, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_7.setFont(font)
        self.lbl_inicio_ingreso_7.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_7.setObjectName("lbl_inicio_ingreso_7")
        self.btn_pendiente_calc = QtWidgets.QPushButton(self.frame_3)
        self.btn_pendiente_calc.setGeometry(QtCore.QRect(60, 320, 241, 41))
        self.btn_pendiente_calc.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"QPushButton:hover{\n"
"color: white;\n"
"border-bottom:1px solid white;\n"
"border-top:1px solid white;\n"
"border-left:1px solid white;\n"
"border-right:1px solid white;\n"
"font-weigth:bold;\n"
"border-radius:18px;\n"
"}")
        self.btn_pendiente_calc.setIcon(icon)
        self.btn_pendiente_calc.setIconSize(QtCore.QSize(20, 20))
        self.btn_pendiente_calc.setObjectName("btn_pendiente_calc")
        self.txt_pendiente_x = QtWidgets.QLineEdit(self.frame_3)
        self.txt_pendiente_x.setGeometry(QtCore.QRect(40, 240, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_pendiente_x.setFont(font)
        self.txt_pendiente_x.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_pendiente_x.setMaxLength(1000000000)
        self.txt_pendiente_x.setObjectName("txt_pendiente_x")
        self.lbl_inicio_ingreso_8 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_8.setGeometry(QtCore.QRect(10, 150, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_8.setFont(font)
        self.lbl_inicio_ingreso_8.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_8.setObjectName("lbl_inicio_ingreso_8")
        self.txt_pendiente_y = QtWidgets.QLineEdit(self.frame_3)
        self.txt_pendiente_y.setGeometry(QtCore.QRect(100, 240, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_pendiente_y.setFont(font)
        self.txt_pendiente_y.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_pendiente_y.setMaxLength(1000000000)
        self.txt_pendiente_y.setObjectName("txt_pendiente_y")
        self.lbl_inicio_ingreso_9 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_9.setGeometry(QtCore.QRect(20, 220, 31, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_9.setFont(font)
        self.lbl_inicio_ingreso_9.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_9.setObjectName("lbl_inicio_ingreso_9")
        self.lbl_inicio_ingreso_11 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_11.setGeometry(QtCore.QRect(10, 370, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_11.setFont(font)
        self.lbl_inicio_ingreso_11.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_11.setObjectName("lbl_inicio_ingreso_11")
        self.lbl_solucion_pendiente = QtWidgets.QLabel(self.frame_3)
        self.lbl_solucion_pendiente.setGeometry(QtCore.QRect(10, 420, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.lbl_solucion_pendiente.setFont(font)
        self.lbl_solucion_pendiente.setStyleSheet("background:transparent;\n"
"color: white;")
        self.lbl_solucion_pendiente.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_solucion_pendiente.setObjectName("lbl_solucion_pendiente")
        self.lbl_inicio_ingreso_12 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_12.setGeometry(QtCore.QRect(10, 180, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_12.setFont(font)
        self.lbl_inicio_ingreso_12.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_12.setObjectName("lbl_inicio_ingreso_12")
        self.lbl_inicio_ingreso_13 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_13.setGeometry(QtCore.QRect(80, 220, 21, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_13.setFont(font)
        self.lbl_inicio_ingreso_13.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_13.setObjectName("lbl_inicio_ingreso_13")
        self.lbl_inicio_ingreso_14 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_14.setGeometry(QtCore.QRect(140, 220, 21, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_14.setFont(font)
        self.lbl_inicio_ingreso_14.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_14.setObjectName("lbl_inicio_ingreso_14")
        self.lbl_inicio_ingreso_15 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_15.setGeometry(QtCore.QRect(170, 220, 21, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_15.setFont(font)
        self.lbl_inicio_ingreso_15.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_15.setObjectName("lbl_inicio_ingreso_15")
        self.lbl_inicio_ingreso_10 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_10.setGeometry(QtCore.QRect(190, 220, 31, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_10.setFont(font)
        self.lbl_inicio_ingreso_10.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_10.setObjectName("lbl_inicio_ingreso_10")
        self.txt_pendiente_x_2 = QtWidgets.QLineEdit(self.frame_3)
        self.txt_pendiente_x_2.setGeometry(QtCore.QRect(220, 240, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_pendiente_x_2.setFont(font)
        self.txt_pendiente_x_2.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_pendiente_x_2.setMaxLength(1000000000)
        self.txt_pendiente_x_2.setObjectName("txt_pendiente_x_2")
        self.lbl_inicio_ingreso_16 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_16.setGeometry(QtCore.QRect(260, 220, 21, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_16.setFont(font)
        self.lbl_inicio_ingreso_16.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_16.setObjectName("lbl_inicio_ingreso_16")
        self.txt_pendiente_y_2 = QtWidgets.QLineEdit(self.frame_3)
        self.txt_pendiente_y_2.setGeometry(QtCore.QRect(280, 240, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_pendiente_y_2.setFont(font)
        self.txt_pendiente_y_2.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_pendiente_y_2.setMaxLength(1000000000)
        self.txt_pendiente_y_2.setObjectName("txt_pendiente_y_2")
        self.lbl_inicio_ingreso_17 = QtWidgets.QLabel(self.frame_3)
        self.lbl_inicio_ingreso_17.setGeometry(QtCore.QRect(320, 220, 21, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_17.setFont(font)
        self.lbl_inicio_ingreso_17.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_17.setObjectName("lbl_inicio_ingreso_17")
        self.btn_regresar_pendiente = QtWidgets.QPushButton(self.page_pendiente)
        self.btn_regresar_pendiente.setGeometry(QtCore.QRect(330, 10, 41, 41))
        self.btn_regresar_pendiente.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"")
        self.btn_regresar_pendiente.setText("")
        self.btn_regresar_pendiente.setIcon(icon1)
        self.btn_regresar_pendiente.setObjectName("btn_regresar_pendiente")
        self.stackedWidget.addWidget(self.page_pendiente)
        self.page_primos = QtWidgets.QWidget()
        self.page_primos.setObjectName("page_primos")
        self.frame_4 = QtWidgets.QFrame(self.page_primos)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 361, 511))
        self.frame_4.setStyleSheet("QFrame{\n"
"background:rgba(0,0,10,0.5);\n"
"border-radius:15px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lbl_inicio_4 = QtWidgets.QLabel(self.frame_4)
        self.lbl_inicio_4.setGeometry(QtCore.QRect(20, 20, 331, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_4.setFont(font)
        self.lbl_inicio_4.setStyleSheet("background:transparent;")
        self.lbl_inicio_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_4.setObjectName("lbl_inicio_4")
        self.lbl_inicio_ingreso_18 = QtWidgets.QLabel(self.frame_4)
        self.lbl_inicio_ingreso_18.setGeometry(QtCore.QRect(10, 100, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_18.setFont(font)
        self.lbl_inicio_ingreso_18.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_18.setObjectName("lbl_inicio_ingreso_18")
        self.btn_primos_inter = QtWidgets.QPushButton(self.frame_4)
        self.btn_primos_inter.setGeometry(QtCore.QRect(60, 390, 241, 41))
        self.btn_primos_inter.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"QPushButton:hover{\n"
"color: white;\n"
"border-bottom:1px solid white;\n"
"border-top:1px solid white;\n"
"border-left:1px solid white;\n"
"border-right:1px solid white;\n"
"font-weigth:bold;\n"
"border-radius:18px;\n"
"}")
        self.btn_primos_inter.setIcon(icon)
        self.btn_primos_inter.setIconSize(QtCore.QSize(20, 20))
        self.btn_primos_inter.setObjectName("btn_primos_inter")
        self.lbl_inicio_ingreso_19 = QtWidgets.QLabel(self.frame_4)
        self.lbl_inicio_ingreso_19.setGeometry(QtCore.QRect(10, 120, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_19.setFont(font)
        self.lbl_inicio_ingreso_19.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_19.setObjectName("lbl_inicio_ingreso_19")
        self.lbl_inicio_ingreso_21 = QtWidgets.QLabel(self.frame_4)
        self.lbl_inicio_ingreso_21.setGeometry(QtCore.QRect(10, 160, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_21.setFont(font)
        self.lbl_inicio_ingreso_21.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_21.setObjectName("lbl_inicio_ingreso_21")
        self.lbl_solucion_interval_primos = QtWidgets.QLabel(self.frame_4)
        self.lbl_solucion_interval_primos.setGeometry(QtCore.QRect(10, 440, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.lbl_solucion_interval_primos.setFont(font)
        self.lbl_solucion_interval_primos.setStyleSheet("background:transparent;\n"
"color:white;")
        self.lbl_solucion_interval_primos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_solucion_interval_primos.setObjectName("lbl_solucion_interval_primos")
        self.vsd_inicio_intervalo = QtWidgets.QSlider(self.frame_4)
        self.vsd_inicio_intervalo.setGeometry(QtCore.QRect(40, 190, 281, 31))
        self.vsd_inicio_intervalo.setOrientation(QtCore.Qt.Horizontal)
        self.vsd_inicio_intervalo.setObjectName("vsd_inicio_intervalo")
        self.lbl_inicio_ingreso_22 = QtWidgets.QLabel(self.frame_4)
        self.lbl_inicio_ingreso_22.setGeometry(QtCore.QRect(10, 260, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_ingreso_22.setFont(font)
        self.lbl_inicio_ingreso_22.setStyleSheet("background:transparent;")
        self.lbl_inicio_ingreso_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_ingreso_22.setObjectName("lbl_inicio_ingreso_22")
        self.vsd_final_intervalo = QtWidgets.QSlider(self.frame_4)
        self.vsd_final_intervalo.setGeometry(QtCore.QRect(40, 290, 281, 31))
        self.vsd_final_intervalo.setOrientation(QtCore.Qt.Horizontal)
        self.vsd_final_intervalo.setObjectName("vsd_final_intervalo")
        self.lbl_inicio_5 = QtWidgets.QLabel(self.frame_4)
        self.lbl_inicio_5.setGeometry(QtCore.QRect(20, 50, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.lbl_inicio_5.setFont(font)
        self.lbl_inicio_5.setStyleSheet("background:transparent;")
        self.lbl_inicio_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio_5.setObjectName("lbl_inicio_5")
        self.btn_regresar_primos = QtWidgets.QPushButton(self.frame_4)
        self.btn_regresar_primos.setGeometry(QtCore.QRect(320, 0, 41, 41))
        self.btn_regresar_primos.setStyleSheet("QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"letter-spacing: 2px;\n"
"text-decoration:none;\n"
"font-size:24px;\n"
"overflow: hidden;\n"
"transition: o.2s;\n"
"}\n"
"")
        self.btn_regresar_primos.setText("")
        self.btn_regresar_primos.setIcon(icon1)
        self.btn_regresar_primos.setObjectName("btn_regresar_primos")
        self.txt_inicio_intervalo = QtWidgets.QLineEdit(self.frame_4)
        self.txt_inicio_intervalo.setGeometry(QtCore.QRect(60, 220, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_inicio_intervalo.setFont(font)
        self.txt_inicio_intervalo.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_inicio_intervalo.setMaxLength(1000000000)
        self.txt_inicio_intervalo.setReadOnly(True)
        self.txt_inicio_intervalo.setPlaceholderText("")
        self.txt_inicio_intervalo.setObjectName("txt_inicio_intervalo")
        self.txt_final_intervalo_2 = QtWidgets.QLineEdit(self.frame_4)
        self.txt_final_intervalo_2.setGeometry(QtCore.QRect(60, 320, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_final_intervalo_2.setFont(font)
        self.txt_final_intervalo_2.setStyleSheet("background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"")
        self.txt_final_intervalo_2.setMaxLength(1000000000)
        self.txt_final_intervalo_2.setReadOnly(True)
        self.txt_final_intervalo_2.setPlaceholderText("")
        self.txt_final_intervalo_2.setObjectName("txt_final_intervalo_2")
        self.stackedWidget.addWidget(self.page_primos)
        Dialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Menu Inicio"))
        self.lbl_inicio.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Calculadora</span></p></body></html>"))
        self.lbl_inicio_ingreso.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#f1f1f1;\">Ingresa</span><span style=\" font-size:11pt; color:#f1f1f1;\"> dos números</span></p></body></html>"))
        self.btn_sumar.setText(_translate("Dialog", "SUMA"))
        self.btn_multiplicar.setText(_translate("Dialog", "Multiplicación"))
        self.txt_num_1.setPlaceholderText(_translate("Dialog", "Número 1"))
        self.txt_num_2.setPlaceholderText(_translate("Dialog", "Número 2"))
        self.lbl_inicio_opcion.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#f1f1f1;\">Oprime</span><span style=\" font-size:11pt; color:#f1f1f1;\"> en la operacion que desees realizar</span></p></body></html>"))
        self.lbl_inicio_saludo_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#f1f1f1;\">Deseas </span><span style=\" font-size:14pt; color:#f1f1f1;\">realizar otra operacion?</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "-----------------------------------------------------------"))
        self.comboBox.setItemText(1, _translate("Dialog", "Resolver ecucaciones cuadraticas"))
        self.comboBox.setItemText(2, _translate("Dialog", "Calcular pendiente de una recta"))
        self.comboBox.setItemText(3, _translate("Dialog", "Numeros primos en un intervalo"))
        self.lbl_inicio_saludo_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#f1f1f1;\">Resultado:</span></p></body></html>"))
        self.lbl_resultado_oper_basicas.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_inicio_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Solución ecuacion </span></p><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">cuadratica</span></p><p><span style=\" font-size:20pt;\"><br/></span></p></body></html>"))
        self.lbl_inicio_ingreso_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Una ecuacion cuadratica tine la</span></p></body></html>"))
        self.btn_cuadratica_solucion.setText(_translate("Dialog", "Solución"))
        self.txt_cuadratica_a.setPlaceholderText(_translate("Dialog", "a"))
        self.lbl_inicio_ingreso_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">forma: ax</span><span style=\" font-size:18pt; color:#ffffff; vertical-align:super;\">2</span><span style=\" font-size:18pt; color:#ffffff;\">+bx+c</span></p></body></html>"))
        self.txt_cuadratica_b.setPlaceholderText(_translate("Dialog", "b"))
        self.txt_cuadratica_c.setPlaceholderText(_translate("Dialog", "c"))
        self.lbl_inicio_ingreso_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">X</span><span style=\" font-size:28pt; color:#f5f5f5; vertical-align:super;\">2</span><span style=\" font-size:28pt; color:#f5f5f5;\">+</span></p></body></html>"))
        self.lbl_inicio_ingreso_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">X+</span></p></body></html>"))
        self.lbl_inicio_ingreso_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">La solucion de tu ecuacion es:</span></p></body></html>"))
        self.lbl_solucion_cuadratica.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_inicio_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Pendiente de una recta</span></p><p><span style=\" font-size:20pt;\"><br/></span></p></body></html>"))
        self.lbl_inicio_ingreso_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Para calcular la pendiente</span></p></body></html>"))
        self.btn_pendiente_calc.setText(_translate("Dialog", "Calcular"))
        self.txt_pendiente_x.setPlaceholderText(_translate("Dialog", "x_1"))
        self.lbl_inicio_ingreso_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">de una recta se requiere de </span></p></body></html>"))
        self.txt_pendiente_y.setPlaceholderText(_translate("Dialog", "y_1"))
        self.lbl_inicio_ingreso_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">(</span></p></body></html>"))
        self.lbl_inicio_ingreso_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">La pendiente de la recta es:</span></p></body></html>"))
        self.lbl_solucion_pendiente.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_inicio_ingreso_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">dos puntos con cordenadas (x,y)</span></p></body></html>"))
        self.lbl_inicio_ingreso_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">,</span></p></body></html>"))
        self.lbl_inicio_ingreso_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">)</span></p></body></html>"))
        self.lbl_inicio_ingreso_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">y</span></p></body></html>"))
        self.lbl_inicio_ingreso_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">(</span></p></body></html>"))
        self.txt_pendiente_x_2.setPlaceholderText(_translate("Dialog", "x_2"))
        self.lbl_inicio_ingreso_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">,</span></p></body></html>"))
        self.txt_pendiente_y_2.setPlaceholderText(_translate("Dialog", "y_2"))
        self.lbl_inicio_ingreso_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#f5f5f5;\">)</span></p></body></html>"))
        self.lbl_inicio_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Números primos </span></p><p><br/></p><p><span style=\" font-size:20pt;\"><br/></span></p></body></html>"))
        self.lbl_inicio_ingreso_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Desliza la barra </span></p></body></html>"))
        self.btn_primos_inter.setText(_translate("Dialog", "Calcular"))
        self.lbl_inicio_ingreso_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">en el intervalo que gustes</span></p></body></html>"))
        self.lbl_inicio_ingreso_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Inicio intervalo:</span></p></body></html>"))
        self.lbl_solucion_interval_primos.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_inicio_ingreso_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Final intervalo:</span></p></body></html>"))
        self.lbl_inicio_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">en un intervalo</span></p><p><span style=\" font-size:20pt;\"><br/></span></p></body></html>"))
import iconos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
